In [7]:
import pandas as pd

# Download latest version
#path = kagglehub.dataset_download("ankushpanday1/global-warming-dataset-195-countries-1900-2023")

#print("Path to dataset files:", path)

df = pd.read_csv("./data/global_warming_dataset.csv")
df.head(10)

,Country,Year,Temperature_Anomaly,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Methane_Emissions,Sea_Level_Rise,...,Waste_Management,Per_Capita_Emissions,Industrial_Activity,Air_Pollution_Index,Biodiversity_Index,Ocean_Acidification,Fossil_Fuel_Usage,Energy_Consumption_Per_Capita,Policy_Score,Average_Temperature
0,Country_103,1913,-1.163537,8.876061e+08,1.627978e+08,54.872178,6.139887e+12,76.710013,8.317626e+06,8.111839,...,82.691409,2.285351,4.060975,150.285539,90.073356,8.025470,39.163860,1480.164332,78.870012,20.825292
1,Country_180,1950,-0.432122,4.497517e+08,4.281359e+08,84.051006,2.601447e+12,68.450021,6.206540e+06,42.025915,...,59.322883,17.411668,85.300604,27.305922,88.289837,8.021719,28.252554,1482.730048,32.600905,28.720587
2,Country_93,2014,0.444954,4.579080e+08,4.926732e+08,72.295357,5.192677e+12,36.725699,1.056885e+06,20.953840,...,94.982931,12.039703,83.804880,216.911429,86.936256,7.647408,61.548382,706.918809,37.671300,15.014084
3,Country_15,2020,-1.171616,5.049503e+08,1.252169e+09,17.259684,8.252128e+12,77.547901,1.986813e+06,45.599595,...,62.064250,2.853957,47.014265,35.869182,44.904331,7.569353,82.423750,2616.238324,86.581725,-1.277086
4,Country_107,1964,-0.564038,6.898891e+08,2.932960e+08,44.438605,8.560746e+12,10.019576,3.313252e+06,7.652150,...,84.431279,19.801173,89.379613,284.263093,8.102916,8.015415,29.964450,4975.683780,20.618406,2.861989
5,Country_72,1926,-1.946218,2.394448e+08,1.441203e+07,6.117781,1.989459e+12,26.163399,8.218906e+06,13.574102,...,36.112468,8.528017,63.807031,172.964007,20.512193,7.874246,67.153067,267.465131,84.672317,37.889804
6,Country_189,1921,-1.362100,1.977445e+08,1.339563e+09,75.554131,9.131238e+12,82.661868,5.160613e+06,1.378949,...,1.237686,7.484364,15.002742,238.288021,67.988814,8.448967,22.046013,3114.698772,72.740043,-7.786539
7,Country_21,1921,1.627624,2.111461e+08,2.410014e+07,25.999981,4.034784e+12,36.773252,5.890986e+06,15.617050,...,90.687488,15.747481,86.194366,150.058727,44.592418,8.436721,58.698935,3519.096247,19.243964,4.206395
8,Country_103,1989,0.541387,7.802026e+08,3.855137e+08,17.797781,6.823672e+12,3.422548,1.313058e+04,36.226933,...,60.895322,10.568785,66.175268,242.089767,93.935792,8.224373,46.630095,2718.348573,89.810124,-5.829195
9,Country_122,1963,0.016534,5.397029e+08,5.508798e+08,8.948443,4.713484e+12,72.875002,5.766624e+06,8.016881,...,77.485505,13.919414,70.265639,153.191500,77.122932,8.190353,52.587813,1745.691747,30.215953,2.473330

In [30]:
decimal_dict = {"Temperature_Anomaly" : 1 ,"CO2_Emissions" : 1 ,"Population" : 0 ,"Forest_Area" : 1, 
                "Renewable_Energy_Usage" : 2, "Methane_Emissions" : 1, "Sea_Level_Rise" : 2, 'Arctic_Ice_Extent' : 3 , 'Urbanization' :1 ,
       'Deforestation_Rate' : 2, 'Extreme_Weather_Events' : 2, 'Average_Rainfall' : 2,
       'Solar_Energy_Potential' : 2, 'Waste_Management' : 2, 'Per_Capita_Emissions' : 2,'Industrial_Activity' : 2 , 'Air_Pollution_Index' : 2 , 'Biodiversity_Index' : 2,
       'Ocean_Acidification' : 2, 'Fossil_Fuel_Usage' : 2,'Energy_Consumption_Per_Capita' : 2, 'Policy_Score' : 2, 'Average_Temperature' : 2, "GDP" : 9 }

def round_decimal_columns(df, decimal_dict):
    for col, decimals in decimal_dict.items():
        if col in df.columns:
            df[col] = round(df[col],decimals)
    return df
df_rounded = round_decimal_columns(df,decimal_dict)
df_rounded.head(5)

,Country,Year,Temperature_Anomaly,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Methane_Emissions,Sea_Level_Rise,...,Waste_Management,Per_Capita_Emissions,Industrial_Activity,Air_Pollution_Index,Biodiversity_Index,Ocean_Acidification,Fossil_Fuel_Usage,Energy_Consumption_Per_Capita,Policy_Score,Average_Temperature
0,Country_103,1913,-1.2,887606100.4,1.627978e+08,54.9,6.139887e+12,76.71,8317625.6,8.11,...,82.69,2.29,4.06,150.3,90.07,8.03,39.16,1480.16,78.87,20.83
1,Country_180,1950,-0.4,449751674.3,4.281359e+08,84.1,2.601447e+12,68.45,6206539.7,42.03,...,59.32,17.41,85.30,27.3,88.29,8.02,28.25,1482.73,32.60,28.72
2,Country_93,2014,0.4,457908034.1,4.926732e+08,72.3,5.192677e+12,36.73,1056885.3,20.95,...,94.98,12.04,83.80,216.9,86.94,7.65,61.55,706.92,37.67,15.01
3,Country_15,2020,-1.2,504950343.4,1.252169e+09,17.3,8.252128e+12,77.55,1986812.8,45.60,...,62.06,2.85,47.01,35.9,44.90,7.57,82.42,2616.24,86.58,-1.28
4,Country_107,1964,-0.6,689889087.8,2.932960e+08,44.4,8.560746e+12,10.02,3313252.1,7.65,...,84.43,19.80,89.38,284.3,8.10,8.02,29.96,4975.68,20.62,2.86

In [29]:
numerical_features = df.select_dtypes(include="number").columns.drop("Year")
df1 = df.copy()
df1= df1.groupby(["Year","Country"])[numerical_features].mean().reset_index().sort_values(by="Year", ascending = False).reset_index(drop=True)
df1

,Year,Country,Temperature_Anomaly,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Methane_Emissions,Sea_Level_Rise,...,Waste_Management,Per_Capita_Emissions,Industrial_Activity,Air_Pollution_Index,Biodiversity_Index,Ocean_Acidification,Fossil_Fuel_Usage,Energy_Consumption_Per_Capita,Policy_Score,Average_Temperature
0,2023,Country_96,-0.100000,4.066161e+08,4.704042e+08,50.700000,7.145684e+12,60.310000,4.705781e+06,30.060000,...,42.795000,10.230000,33.425000,157.200000,33.285000,8.360000,22.405000,1560.460000,31.665000,8.440000
1,2023,Country_95,-0.450000,6.394889e+08,5.765570e+08,71.400000,6.370411e+12,31.315000,6.580553e+06,15.865000,...,2.655000,16.745000,31.650000,240.000000,85.595000,7.995000,34.020000,2305.420000,65.885000,14.290000
2,2023,Country_94,0.437500,2.786647e+08,7.830261e+08,47.637500,4.564758e+12,46.892500,5.130695e+06,26.930000,...,46.575000,11.238750,48.892500,150.612500,31.582500,7.903750,50.785000,2181.606250,43.202500,21.620000
3,2023,Country_93,-1.166667,3.989293e+08,8.674566e+08,61.033333,6.447232e+12,42.510000,5.485669e+06,31.406667,...,33.926667,12.716667,36.443333,168.233333,59.596667,7.763333,48.183333,1853.840000,56.726667,13.090000
4,2023,Country_92,0.400000,3.926497e+08,7.230433e+08,43.050000,6.609551e+12,58.830000,5.289852e+06,11.750000,...,63.965000,12.405000,81.070000,167.500000,84.010000,7.695000,48.185000,120.415000,39.685000,19.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23792,1900,Country_86,0.400000,5.124535e+08,6.193448e+08,66.933333,4.943191e+12,46.273333,6.745289e+06,16.573333,...,37.026667,7.223333,45.236667,183.566667,74.543333,8.046667,66.130000,961.393333,55.856667,10.566667
23793,1900,Country_87,-1.225000,6.009543e+08,8.747814e+08,37.225000,4.818341e+12,53.237500,5.026183e+06,18.155000,...,64.542500,12.330000,78.332500,147.600000,65.145000,7.805000,65.812500,2579.425000,20.320000,10.810000
23794,1900,Country_88,-0.600000,7.728352e+08,6.165350e+07,23.500000,4.394689e+12,59.000000,8.739675e+06,13.060000,...,89.400000,0.110000,87.410000,208.400000,99.930000,8.470000,95.230000,2518.790000,9.370000,8.820000
23795,1900,Country_89,-1.075000,3.597489e+08,9.759180e+08,68.850000,4.434546e+12,62.450000,7.260697e+06,29.447500,...,30.882500,12.437500,70.920000,121.375000,29.337500,7.990000,39.535000,2348.532500,29.140000,17.775000
23796,1900,Country_1,-0.325000,3.984644e+08,3.750466e+08,27.850000,4.573252e+12,60.185000,5.169077e+06,24.480000,...,73.045000,10.580000,57.202500,160.900000,45.790000,8.080000,52.425000,2657.027500,42.940000,5.505000